from __future__ import annotations

from dataclasses import dataclass

METADATA_COLUMNS = (
    "source",
    "retrieved_at_utc",
    "source_updated_at_utc",
    "schema_version",
    "content_hash",
)


@dataclass(frozen=True)
class ArtifactSchema:
    name: str
    columns: tuple[str, ...]
    primary_key: tuple[str, ...]
    append_only: bool = False


ARTIFACT_SCHEMAS: dict[str, ArtifactSchema] = {
    "games": ArtifactSchema(
        "games",
        (
            "game_id",
            "season",
            "week",
            "game_type",
            "kickoff_utc",
            "away_team",
            "home_team",
            "away_score",
            "home_score",
            "result",
            "total",
            "away_rest",
            "home_rest",
            "away_moneyline",
            "home_moneyline",
            "spread_line",
            "away_spread_odds",
            "home_spread_odds",
            "total_line",
            "under_odds",
            "over_odds",
            "roof",
            "surface",
            "temp",
            "wind",
            *METADATA_COLUMNS,
        ),
        ("game_id",),
    ),
    "team_metrics": ArtifactSchema(
        "team_metrics",
        (
            "game_id",
            "season",
            "week",
            "kickoff_utc",
            "team_id",
            "opponent_team_id",
            "is_home",
            "games_available",
            "off_pass_epa",
            "def_pass_epa",
            "off_rush_epa",
            "def_rush_epa",
            "off_pass_success_rate",
            "def_pass_success_rate",
            "off_rush_success_rate",
            "def_rush_success_rate",
            "feature_as_of_utc",
            "half_life",
            *METADATA_COLUMNS,
        ),
        ("game_id", "team_id"),
    ),
    "market_odds": ArtifactSchema(
        "market_odds",
        (
            "snapshot_id",
            "provider_event_id",
            "game_id",
            "commence_time_utc",
            "bookmaker_key",
            "bookmaker_title",
            "bookmaker_group",
            "market",
            "selection",
            "point",
            "canonical_line",
            "american_price",
            "decimal_price",
            "implied_probability",
            "vig_free_probability",
            "overround",
            "last_update_utc",
            *METADATA_COLUMNS,
        ),
        ("snapshot_id", "provider_event_id", "bookmaker_key", "market", "selection"),
        append_only=True,
    ),
    "injuries": ArtifactSchema(
        "injuries",
        (
            "season",
            "week",
            "team_id",
            "player_id",
            "full_name",
            "position",
            "injury_status",
            "practice_status",
            "report_primary_injury",
            "report_secondary_injury",
            "snap_share_impact",
            "replacement_quality",
            *METADATA_COLUMNS,
        ),
        ("season", "week", "team_id", "player_id"),
    ),
    "player_usage": ArtifactSchema(
        "player_usage",
        (
            "season",
            "week",
            "game_id",
            "player_id",
            "player_name",
            "team_id",
            "position",
            "offense_snaps",
            "offense_pct",
            "defense_snaps",
            "defense_pct",
            "special_teams_snaps",
            "special_teams_pct",
            *METADATA_COLUMNS,
        ),
        ("season", "week", "game_id", "player_id", "team_id"),
    ),
    "coverage_metrics": ArtifactSchema(
        "coverage_metrics",
        (
            "season",
            "week",
            "game_id",
            "team_id",
            "metric_name",
            "metric_value",
            "availability_status",
            *METADATA_COLUMNS,
        ),
        ("season", "week", "game_id", "team_id", "metric_name"),
    ),
    "model_history": ArtifactSchema(
        "model_history",
        (
            "model_version",
            "created_at_utc",
            "command",
            "development_end_season",
            "test_season",
            "spec_hash",
            "feature_hash",
            "artifact_path",
            "status",
            "spread_alpha",
            "total_alpha",
            "spread_brier",
            "spread_log_loss",
            "spread_market_brier",
            "spread_market_log_loss",
            "total_brier",
            "total_log_loss",
            "total_market_brier",
            "total_market_log_loss",
            "notes",
            *METADATA_COLUMNS,
        ),
        ("model_version", "command", "created_at_utc"),
        append_only=True,
    ),
    "bet_log": ArtifactSchema(
        "bet_log",
        (
            "bet_id",
            "timestamp",
            "season",
            "week",
            "game_id",
            "market",
            "selection",
            "line",
            "price",
            "book",
            "stake",
            "bankroll",
            "model_probability",
            "market_fair_probability",
            "expected_roi",
            "model_version",
            "data_timestamp",
            "closing_line",
            "closing_price",
            "vig_free_closing_probability",
            "probability_clv",
            "result",
            "profit_loss",
            "decision",
            "reason",
            *METADATA_COLUMNS,
        ),
        ("bet_id",),
        append_only=True,
    ),
    "model_predictions": ArtifactSchema(
        "model_predictions",
        (
            "prediction_id",
            "model_version",
            "model_artifact_hash",
            "model_spec_hash",
            "policy_hash",
            "git_commit",
            "snapshot_id",
            "provider_event_id",
            "game_id",
            "season",
            "week",
            "kickoff_utc",
            "market",
            "orientation",
            "prediction_created_at_utc",
            "snapshot_retrieved_at_utc",
            "feature_as_of_utc",
            "feature_input_hash",
            "feature_row_hash",
            "pinnacle_updated_at_utc",
            "pinnacle_line",
            "pinnacle_orientation_price",
            "pinnacle_other_price",
            "pinnacle_orientation_no_vig_probability",
            "pinnacle_overround",
            "consensus_line",
            "consensus_probability",
            "consensus_status",
            "retail_books_count",
            "raw_adjustment",
            "adjustment_weight",
            "final_projection",
            "raw_non_push_win_probability",
            "calibrated_non_push_win_probability",
            "model_win_probability",
            "model_push_probability",
            "model_loss_probability",
            "uncertainty_status",
            "eligibility_status",
            "decision",
            "pass_reason",
            *METADATA_COLUMNS,
        ),
        ("prediction_id",),
        append_only=True,
    ),
    "prospective_evaluations": ArtifactSchema(
        "prospective_evaluations",
        (
            "evaluation_id",
            "prediction_id",
            "model_version",
            "game_id",
            "season",
            "week",
            "kickoff_utc",
            "market",
            "orientation",
            "settled_at_utc",
            "selection_rule_version",
            "canonical_snapshot_id",
            "prediction_created_at_utc",
            "feature_as_of_utc",
            "decision_snapshot_id",
            "closing_snapshot_id",
            "decision_line",
            "decision_orientation_price",
            "decision_other_price",
            "decision_market_probability",
            "closing_line",
            "closing_orientation_price",
            "closing_other_price",
            "closing_market_probability",
            "final_projection",
            "model_non_push_win_probability",
            "model_win_probability",
            "model_push_probability",
            "model_loss_probability",
            "actual_value",
            "result",
            "eligible_non_push",
            "exclusion_reason",
            "model_brier",
            "market_brier",
            "model_log_loss",
            "market_log_loss",
            "projection_error",
            "market_projection_error",
            "market_probability_movement",
            "decision_price_clv",
            "decision_line_clv",
            "line_clv",
            "closing_contract_win_probability",
            "closing_contract_push_probability",
            "closing_contract_loss_probability",
            "closing_contract_ev",
            "key_numbers_crossed_json",
            "key_number_movement",
            "clv_status",
            "reconciliation_status",
            *METADATA_COLUMNS,
        ),
        ("evaluation_id",),
        append_only=True,
    ),
}


def artifact_csv_name(name: str) -> str:
    return f"{name}.csv"
